### ISSUE TITLE
badmatch in emysql_tcp.rtl

### ISSUE THREAD

**Issue by d0rc** [Eonblast/Emysql#124]
It happens time to time:

Error in process <0.3037.0> with exit value: {{badmatch,{error,closed}},[{emysql_tcp,send_and_recv_packet,3,[{file,"src/emysql_tcp.erl"},{line,38}]},{emysql,'-monitor_work/3-fun-0-',2,[{file,"src/emysql.erl"},{line,727}]}]}

I've been using old version of emysql in that project since january '14, after upgrade to master I've started seeing such errors in log.

**Comment by d0rc** [comment]
It happens if system has no job to do for a long time. All connections get closed by loadbalancer (in front of mysql cluster), and then I'll have to try to get results from pool several times (the pool size) before I can get any results.

**Comment by jlouis** [comment]
Ah, I see what is wrong in the code flow. The problem is an improper handling of connection resets. The old code would do

```
...
{error, Reason} -> exit({failed, Reason})
```

which means we will have the code exiting with exit reason `{failed, closed}`. This is explicitly handled in `monitor_work/3` and the connection is reset in this case. With the new semantics, we just crash, but then the connection is not reset. At least this explains what the problem is.

I have pushed a patch. Could you check if it works for you?

**Comment by d0rc** [comment]
@jlouis updated emysql version, will write in couple of hours if it helps.

**Comment by jlouis** [comment]
Thanks. I have deliberately only added the `closed` case for now. I want to know what kind of trouble people run into when they can't send on a MySQL socket.

**Comment by d0rc** [comment]
@jlouis thanks! it helped, things are back to normal:)

**Comment by jlouis** [comment]
Awesome, getting rid of this one then
