### ISSUE TITLE
emysql_util:encode will fail when Val contains unicode text

### ISSUE THREAD

**Issue by fangjian601** [Eonblast/Emysql#14]
emysql_util:encode use erlang:list_to_binary which not support unicode text, this will cause badarg error

any hint to fix it?

**Comment by hdiedrich** [comment]
Hi  方建,

thanks for sharing your observation. I am not sure it's a bug, or should be changed. Please let me know if this is a practical concern you ran into, or a conclusion entirely from code analysis?

Do you have a practical example that causes an error?

If you look at it in context, as far as I can see, the encoding using list_to_binary is only ever triggered when you pass in a string in list notation as a **parameter to a prepared statement**.

If the parameter is passed in as binary, list_to_binary is not used. If you were to pass in a UTF-8 binary, say <<björn/utf8>>, list_to_binary would not be used.

Cfr. "The default Unicode encoding in Erlang is in binaries UTF-8, which is also the format in which built in functions and libraries in OTP expect to find binary Unicode data." http://www.erlang.org/doc/man/unicode.html

So if you are using UTF-8, unicode, for practical purposes, you would at this point more likely pass a binary in to the parameter set function, not a list of UTF-8 integers. Hence list_to_binary() is not used and will not cause an error.

If you had the unicode as list at that point, my question would be why and what for? Let me know if I am overlooking a use case there.

Regardless, unicode:character_to_binary() _could_ be used in the instance but I am not sure that it would be a good idea to add it at this point, and make Emysql depending on the unicode module, and possibly create a source of confusion. 

I think it should stay as it is. But I will try to keep an eye on the issue and do some more tests. Let me know if you feel I got something wrong,

thanks,
Henning

**Comment by fangjian601** [comment]
Hi henning:

Thanks for your comment about my problem.  

As you said 

"If the parameter is passed in as binary, list_to_binary is not used. If you were to pass in a UTF-8 binary, say <<björn/utf8>>, list_to_binary would not be used."

I've got your point, I'll pass UTF-8 binary to prepared statement parameter to solve this problem :)

**Comment by hdiedrich** [comment]
Did you have the practical case that you had unicode integers in a string list?

So that you _actually_ triggered the error?

**Comment by fangjian601** [comment]
Yes, I actually triggered the error

A table column in my database maybe contains some unicode integers

**Comment by hdiedrich** [comment]
Hi 方建,

I made some careful changes and added Common Tests ('make test') to make sure that they are consistent.

It was as tricky as I expected: the main problem is that latin-1 characters > 127 are represented by two bytes in UTF-8 and that 128 - 255 are basically illegal UTF-8 codes. So at some point the guessing starts. And the problems are really almost entirely restricted to parameters for prepared statements. The idea there was that you can throw any type in. Now it even has become 'any type or encoding': list string (latin-1 or UTF-8) or any binary (ditto).

If you like to look at the latest changes, some might be surprising. But it's the most consistent I could find. Especially please take a look at the test functions with names starting on straight\* in test/unicode_SUITE.erl. They illustrate in 16 cases what happens when (latin-1 list string, latin-1 binary, utf-8 list string, ... ).

Even though it was an effort to get it up and running, I am not sure if the automatic string conversion should stay in at all. It's just not transparent enough, what happens when. Ample chances to shoot yourself in the foot. It may be better to require users to always use binaries with the library.

I'd be happy to hear from you, if anything breaks for you with the newest commit, or if it is backwards compatible, as it should.

Best,
Henning
