### ISSUE TITLE
return value problem on execute stored procedure

### ISSUE THREAD

**Issue by seven1240** [Eonblast/Emysql#4]
Hi,

please see https://gist.github.com/790941, the SP was created by

  create procedure sp_hello() begin select \* from hello_table; end;

If I call run2(4) which is the same as the original code, everything is fine.

If I call run3(4), as the gist shows, it returns #result_packet and #ok_packet alternatively. Should I take this as normal and run twice if there is an SP ?

If I call run2(4) followed by run3(4), (uncomment the run2 line in the gist), then run2() start behaves like run3().

Can you look into it? Thanks.

**Comment by Eonblast** [comment]
Thanks, this was a bug, likely from a MySQL client-server protocol update.

Stored Procedures work now as expected, but return a list of result packages, instead of one result package. The first package contains the data, the second is an ok_package. This makes the results from a SELECT differ slightly from that of a call of a stored procedure, returning the same result set. But accurately reflects the actual server behavior and should be more robust.

**Comment by Eonblast** [comment]
See sample samples/e_stored_procedure.erl

```
-module(e_stored_procedure).
-export([run/0]).

run() ->

    crypto:start(),
    application:start(emysql),

    io:format("~nConnect~n-------~n", []),
    emysql:add_pool(hello_pool, 1,
        "hello_username", "hello_password", "localhost", 3306,
        "hello_database", utf8),

    io:format("~nCreate Record~n-------------~n", []),
    emysql:execute(hello_pool,
        <<"INSERT INTO hello_table SET hello_text = 'Hello World!'">>),

    io:format("~nTest Select~n-----------~n", []), 
    Result1 = emysql:execute(hello_pool,
    <<"select * from hello_table limit 2">>),
    io:format("~p~n", [Result1]),

    io:format("~nCreate Stored Procedure~n-----------------------~n", []),
    Result2 = emysql:execute(hello_pool,
    <<"create procedure sp_hello() begin select * from hello_table limit 2; end">>),
    io:format("~p~n", [Result2]),

    io:format("~nCall Stored Procedure~n---------------------~n", []),
    Result3 = emysql:execute(hello_pool,
        <<"call sp_hello();">>),
    io:format("~p~n", [Result3]),

    done.
```
