### ISSUE TITLE
Save binary data as is

### ISSUE THREAD

**Issue by valinurovam** [Eonblast/Emysql#40]
Tell me pls, how can i save binary data as is with prepared statements if my connection work on utf8 encoding.
Now it is imposible, cause all given variables translated with unicode:characters_to_binary. and if my binary list dont has utf8 bytes, they converted. Its abnormal. I need to save my bin data as is.

**Comment by hdiedrich** [comment]
The conversion should work in either direction, you should get back out what you put in. Except if you have a different setting on the server or for the database and tables so that conversion cascade and loose information.

Maybe I am not seeing the point accurately. Does the problem persist for you?

**Comment by jlouis** [comment]
The problem here is that a row has type BLOB or BINARY. So what we are to send is raw binary data without any kind of translation. The default code will regard any `binary()` from Erlang as something that should be modified according to `Encoding` so in the case of `utf8` we will try to mangle the binary. This often fails of course, since random binaries are not at all valid UTF8.

**Comment by jlouis** [comment]
This has now been fixed. We send all binary data "as is" now on the master branch. This means problems like these should have disappeared.
