### ISSUE TITLE
race condition in wait_for_connection/1

### ISSUE THREAD

**Issue by chaos-ad** [Eonblast/Emysql#9]
process, that asks for a connection, will be placed in the queue, but may be skipped as timeouted because of using hack with process_info in pass_connection_to_waiting_pid.
Since it may not be successfull enough to finish receiving response in gen_server:call.

**Comment by Eonblast** [comment]
In other words: There could be a race when the connection manager queues the request of a waiting monitor_work process (lurking in synch execution of gen_server call) and then the manager process turns around and is FASTER than the queued process to find a free connection and trying to assign it to it THAN the formerly waiting, now queued process is to find its way back into the monitor_work function. 

The process would get "thrown away", deleted from the queue head, if it is encountered but NOT found waiting in the function monitor_work at that moment, which could happen if it had not had processor time to get back out of the gen_server guts and back to that function.

**Comment by Eonblast** [comment]
Tag issue9 in dev branch seems to confirm the possibility of this race. It has a brutalized gen_server.erl module that makes a queued process hang for some seconds and miss its turn when a connection becomes available, then die waiting for it, in a timeout. 

What can't happen is a race during the time "in the gen_server" while the gen_server process is at it, because pass_connection_to_waiting_pid() is itself called by the gen_server process, exclusively. That obviously forestalls a race between most of the gen_server internals and pass_connection_to_waiting_pid(). This is also seen below, the first 'race provocation' does not work. The problem can only appear in the part of the gen_server() source that is  executed by the calling process, not the gen_server process itself.

Sample output for Emysql's modified hello.erl, built with that tag:

```
$ make
$ erlc hello.erl
$ erl -pa ./ebin -s hello run -s init stop -noshell
main: start ... 
main: pool ... 
main: fork ... 
main: wait ... 
process <0.42.0> >>> insert ... 
process <0.43.0> >>> insert ... 
process <0.42.0> immediately gets a free connection = no queueing 
process <0.43.0> must wait for a free connection, will be queued
process <0.42.0> now puts connection to use
process <0.43.0> is now tricked to enter delaying gen_server:call()
process <0.43.0> has been queued to wait for a connection
           ... (now in {current_function,{gen,do_call,4}})
           ... it now waits arround here to provoke a race
           ... trying to cause a problem by not returning to wait_for_connection() in time ...
process <0.42.0> is done using its connection
--- unlock connection is called (misleading name: it may not end up unlocked but immediately re-assigned) ---
process <0.43.0> ... has wasted enough time in {current_function,
                                                {gen,do_call,4}} and returns now
process <0.43.0> got its response but is held in gen_server:call() to produce a race
--- unlock connection is HANDLED (misleading name: it may not end up unlocked but immediately re-assigned) ---
--- a connection is ready to be assigned to a waiting process ---
... and some process is waiting in the queue for it:
process <0.43.0> is fetched from the wait queue head.
Warning: dropping wait queue head pid <0.43.0>
so, again: ...
--- a connection is ready to be assigned to a waiting process ---
... but no process is waiting: unlock it
process <0.43.0> is now released from forced sleep in gen_server:call() ... and should now be late
process <0.43.0> dies waiting for a connection, thinking it's still in the queue.
```

**Comment by hdiedrich** [comment]
Problem is demonstrated in hello.erl of 
https://github.com/Eonblast/Emysql/tree/c27f383f684b3cc6fc3a6c8f5a2db46e4c9deb53

Possible remedy using is_process_alive()
https://github.com/Eonblast/Emysql/commit/8214acba7da7013d1ad5dcef3b15f269deafaeef

That (dev) is a strictly experimental branch, both commits trace heavily, have waits built in and a changed gen_server.erl. 

Another branch (dev2) has only the possible remedy and no experimental add ins:
https://github.com/Eonblast/Emysql/commit/f17b3a1525c0c67adeaa23d5144adc991c18cdee

**Comment by ransomr** [comment]
There are two other race conditions in the connection manager code. Both are more rare than the possibility that the waiting process has is not yet waiting in wait_for_connection (as described above):
1. The process W calls wait_for_connection. lock_connection returns unavailable. But before W calls start_wait another process calls pass_connection. Because W isn't yet in the wait list, W is not given the connection.
2. There is a race condition between the lock_timeout and a connection being returned. It is possible that W is sent a connection message at exactly the same time as it times out. If that happens the connection will be abandoned.

**Comment by hdiedrich** [comment]
Brilliant! Thanks so much for clearing this up.
